import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { getallchanneldetail } from "../actions/channeldataaction";
import ChannelDetails from "../components/channeldetailscomponent";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [channeldata, setchanneldata] = useState(null);
  // setInterval(() => {
  //   getallchanneldetail().then((data) => {
  //     if (data) {
  //       console.log("trigger");
  //       setchanneldata(data);
  //     }
  //   });
  // }, 5000);

  useEffect(() => {
    const intervalCall = setInterval(() => {
      getallchanneldetail().then((data) => {
        if (data) {
          console.log("trigger");
          setchanneldata(data);
        }
      });
    }, 10000);
    return () => {
      // clean up
      clearInterval(intervalCall);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{/* <div>sssssssss</div> */}</div>
      {channeldata ? (
        <div>
          <ChannelDetails data={channeldata} />
        </div>
      ) : null}
    </div>
  );
};

export default Home;
